#—- Build image --#
# docker build -t kamermanpr/gabapentinoids:v1.1 .

#-- The latest image can be downloaded from Docker Hub --#
# docker pull kamermanpr/gabapentinoids:v1.1

#-- Run command --#
# docker run --name pain -d -p 8787:8787 -e USER=user -e PASSWORD=password kamermanpr/gabapentinoids:v1.1

#-- Login to RStudio --#
# In your browser, navigate to: localhost:8787
# Username: user
# Password: password

#-- Get the verse rocker image --#

FROM rocker/verse:4.2.0

MAINTAINER Peter Kamerman <peter.kamerman@gmail.com>

#-- Install extra packages --#

RUN Rscript -e "install.packages(c('ggthemes', 'kableExtra', 'lspline', 'moderndive', 'MuMIn', 'patchwork', 'quantreg', 'skimr', 'forecast', 'tseries'), dependencies = TRUE)"
